services:
  secretgpt:
    image: ghcr.io/mrgarbonzo/secretgpt:tokens-latest
    container_name: secretgpt-hub
    restart: unless-stopped

    # All configuration is now hardcoded in the Dockerfile
    # Only the SECRET_AI_API_KEY needs to be provided at runtime
    environment:
      # Secret AI API Key - REQUIRED at runtime
      # Provide via SecretVM environment configuration or docker-compose override
      - SECRET_AI_API_KEY=${SECRET_AI_API_KEY:-sk-Y4bjL5ZrB4RVLgCL4vxDEyFZWTqsKjF-UYP3nFTXSFEzZlHB_qoIOXeyRDdlMuwGo-1pjHsO}

      # MCP Service URL - use host.docker.internal to access host services from container
      - SECRET_MCP_URL=${SECRET_MCP_URL:-http://host.docker.internal:8002}
    
    # Network configuration
    ports:
      - "80:8000"
    extra_hosts:
      - host.docker.internal:host-gateway
    
    # Health monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s