version: '3.8'

services:
  secretgpt:
    image: ghcr.io/mrgarbonzo/secretgpt:attest-tools
    container_name: secretgpt-hub
    restart: unless-stopped
    ports:
      - "8003:8000"
    environment:
      - SECRET_AI_API_KEY=${SECRET_AI_API_KEY:-bWFzdGVyQHNjcnRsYWJzLmNvbTpTZWNyZXROZXR3b3JrTWFzdGVyS2V5X18yMDI1}
      - SECRETGPT_HUB_HOST=0.0.0.0
      - SECRETGPT_HUB_PORT=8000
      - SECRETGPT_RUN_MODE=service
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - SECRETGPT_ENABLE_WEB_UI=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3