# secretGPT Hub Docker Compose - Development Configuration
# This configuration is designed for development and testing to avoid restart loops
# REFERENCE: DETAILED_BUILD_PLAN.md Single Container (Phases 1-3)

version: '3.8'

services:
  secretgpt-dev:
    image: ghcr.io/mrgarbonzo/secretgpt:latest
    container_name: secretgpt-hub-dev
    ports:
      - "8003:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # REFERENCE: secretAI-setting-up-environment.txt
      - SECRET_AI_API_KEY=${SECRET_AI_API_KEY:-bWFzdGVyQHNjcnRsYWJzLmNvbTpTZWNyZXROZXR3b3JrTWFzdGVyS2V5X18yMDI1}
      
      # Hub Configuration
      - SECRETGPT_HUB_HOST=0.0.0.0
      - SECRETGPT_HUB_PORT=8000
      
      # Run mode: test for development (avoids infinite loops)
      - SECRETGPT_RUN_MODE=test
      
      # Environment settings
      - ENVIRONMENT=development
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      
      # Phase 2: Web UI configuration (disabled for test mode)
      - SECRETGPT_ENABLE_WEB_UI=false
      
      
      # Phase 4: MCP configuration (disabled for Phase 1)
      - MCP_ENABLED=false
      - MCP_SECRET_NETWORK_URL=
    
    # Mount source code for development (commented out for image-based deployment)
    # volumes:
    #   - ./secretGPT:/app/secretGPT
    #   - ./requirements.txt:/app/requirements.txt
    
    # Health check - disabled for development to reduce noise
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s
    
    # Restart policy: no restart for development (prevents loops)
    restart: "no"
    
    # Resource limits (minimal for development)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Optional: Development database service (if needed in future phases)
  # postgres-dev:
  #   image: postgres:15
  #   container_name: secretgpt-db-dev
  #   environment:
  #     - POSTGRES_DB=secretgpt_dev
  #     - POSTGRES_USER=secretgpt
  #     - POSTGRES_PASSWORD=dev_password
  #   ports:
  #     - "5432:5432"
  #   restart: "no"