version: '3.8'

services:
  secretgpt:
    image: ghcr.io/mrgarbonzo/secretgpt:latest
    container_name: secretgpt-hub
    restart: unless-stopped
    ports:
      - "80:8000"
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_AI_API_KEY=${SECRET_AI_API_KEY}
      - SECRETGPT_HUB_HOST=0.0.0.0
      - SECRETGPT_HUB_PORT=8000
      - SECRETGPT_RUN_MODE=service
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - SECRETGPT_ENABLE_WEB_UI=true
      - SECRETGPT_ATTESTATION_ENDPOINT=https://localhost:29343/cpu.html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
