version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    format: '%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/attestation_hub.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  attestation_hub:
    level: INFO
    handlers: [console, file]
    propagate: false

  uvicorn:
    handlers: [console]
    level: INFO

  httpx:
    handlers: [console]
    level: WARNING

root:
  level: INFO
  handlers: [console]