vms:
  secretai:
    endpoint: "https://secretai.scrtlabs.com:29343"
    type: "secret-ai"
    parsing_strategy: "rest_server"
    timeout: 30
    retry_attempts: 3
    fallback_strategy: null
    health_check_path: "/status"
    tls_verify: false
    
  secretgpt:
    endpoint: "https://localhost:29343"
    type: "secret-gpt"
    parsing_strategy: "rest_server"
    timeout: 30
    retry_attempts: 3
    fallback_strategy: "hardcoded"
    health_check_path: "/status"
    tls_verify: false